#!/bin/bash
# ROS2 Humble on macOS — Native install via RoboStack (no VM, no Docker)
# Supports: Apple Silicon (M1/M2/M3/M4/M5) and Intel Macs

set -e

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'
ok()   { echo -e "${GREEN}✓${NC} $1"; }
info() { echo -e "${BLUE}→${NC} $1"; }
warn() { echo -e "${YELLOW}⚠${NC}  $1"; }
die()  { echo -e "${RED}✗ ERROR:${NC} $1"; exit 1; }

ENV_NAME="ros2"
MAMBA=""

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║   ROS2 Humble — macOS Native Setup       ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════╝${NC}"
echo ""

# macOS version check
MACOS_VER=$(sw_vers -productVersion)
ARCH=$(uname -m)
info "macOS $MACOS_VER | $ARCH"
[[ "$ARCH" != "arm64" && "$ARCH" != "x86_64" ]] && die "Unsupported architecture: $ARCH"
echo ""

# Find mamba — check all common install locations
find_mamba() {
    for path in \
        "$HOME/miniforge3/bin/mamba" \
        "$HOME/mambaforge/bin/mamba" \
        "$HOME/miniconda3/bin/mamba" \
        "$HOME/anaconda3/bin/mamba" \
        "/opt/homebrew/bin/mamba" \
        "/usr/local/bin/mamba"; do
        [ -f "$path" ] && echo "$path" && return
    done
    command -v mamba 2>/dev/null && return
    echo ""
}

MAMBA=$(find_mamba)

if [ -z "$MAMBA" ]; then
    warn "mamba not found. Installing Miniforge3 (includes mamba)..."
    if [ "$ARCH" = "arm64" ]; then
        URL="https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh"
    else
        URL="https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-x86_64.sh"
    fi
    curl -fsSL "$URL" -o /tmp/miniforge.sh
    bash /tmp/miniforge.sh -b -p "$HOME/miniforge3"
    source "$HOME/miniforge3/etc/profile.d/conda.sh"
    source "$HOME/miniforge3/etc/profile.d/mamba.sh"
    MAMBA="$HOME/miniforge3/bin/mamba"
    ok "Miniforge3 installed at ~/miniforge3"
else
    ok "Found mamba: $MAMBA"
fi

CONDA_BASE=$(dirname "$(dirname "$MAMBA")")
info "Conda base: $CONDA_BASE"
echo ""

# Check if env already exists
if [ -d "$CONDA_BASE/envs/$ENV_NAME" ]; then
    warn "Environment '$ENV_NAME' already exists."
    read -p "  Reinstall from scratch? [y/N] " -n 1 -r; echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        info "Removing existing environment..."
        "$MAMBA" env remove -n "$ENV_NAME" -y
    else
        ok "Keeping existing environment. Run 'make run' to launch turtlesim."
        exit 0
    fi
fi

echo ""
info "Installing ROS2 Humble + turtlesim (5-10 min on first run)..."
info "Packages: ros-humble-desktop, ros-humble-turtlesim, colcon, rosdep"
echo ""

"$MAMBA" create -n "$ENV_NAME" \
    -c robostack-staging \
    -c conda-forge \
    --no-channel-priority \
    ros-humble-desktop \
    ros-humble-turtlesim \
    ros-humble-rviz2 \
    ros-humble-rosbag2 \
    colcon-common-extensions \
    python=3.11 \
    -y

echo ""
ok "ROS2 Humble installed successfully!"
echo ""

# Write the activate helper once
ACTIVATE_HELPER="$HOME/.ros2_activate"
cat > "$ACTIVATE_HELPER" <<EOF
# Auto-generated by ros2-turtlesim-mac setup.sh
source "$CONDA_BASE/etc/profile.d/conda.sh"
conda activate $ENV_NAME
EOF
ok "Wrote activate helper to ~/.ros2_activate"

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║   Setup complete!                        ║${NC}"
echo -e "${BOLD}╠══════════════════════════════════════════╣${NC}"
echo -e "${BOLD}║  make run      → launch turtlesim        ║${NC}"
echo -e "${BOLD}║  make demo     → animated demo           ║${NC}"
echo -e "${BOLD}║  make check    → verify install          ║${NC}"
echo -e "${BOLD}║  make examples → list example scripts    ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════╝${NC}"
echo ""
